#Counting DNA Nucleotides
#Given a DNA strong of length at most 1000 nt
#Return 4 integers, separated by spaces, counting the respective
	#number of times that A, G, C, T appear in the string
	

DNAin = "GTGTTCAACTCTGGGTGGGACATTAATGGGGCTCGAAATACGGCGAACGTCCCCGCAGGCTATTAACGCAAAACGCATATTCCTCCGTCGGTCCTTTCTTGAGCTAAGCACCCTCTACTGGATTCTAAGAGTTGCCCCGAATTCGAAAGGGGTAGGGGTCAAAGTTCCACAGAAACAGCACGTTTGCTCGAATGATGACCTACGTCCTGTCTAACTTGTGCCGACCGTTTAGTTTACGCTTGGAGATGGCTTCGATGCAGATCGCGCTGGGGTACGGGTGCGTATACTTTGGGGACTTCGGAACACGGGAGCAACCTACAAGACGCTGCCGTTAGTGAAGTCTCCCCTCTCCGCATAAAGCATCTAGGCACTCGCTCCCAAGTCTAGGAACTGACTACAGGATGAACTTTCAGATATTGTATCAATACAGTTGGGTGGCAACTGAACGAGGATTTACACCCTTTAAATACGTACGTTCTGCTGACGCTTGAAACGACAGCCTCTACCGCTTTCGGAAACCTCTAATCTTGCTAACTCTCGACTGAGGGCGCGTTTAATCTGTCATACAGCGAACGCCAGTAAAAGAAGTGTGTGGCGAAAGACACGGTATGCGCTTCCGGTAACTCAGAGGTTCTTCAGAGCGTAAATAGATTAGTCGGTGAACGGCAAAACAGCCCCCAAGGGTTCATTAGCTACTGACCATCTCCAAGCATTGCTCACCCGGATCATTATTGTGCCCCGCTAGAGCCGATCCTGAGTTTAACCTCTCACTCAAATAGAGTTGGCCTCGTCCTATTTGGGTGATGGTCCACTG"
A = DNAin.count("A")
G = DNAin.count ("G")
C = DNAin.count("C")
T = DNAin.count("T")
print(str(A) + " " + str(C) + " " + str(G) + " " +str(T))


